### ISSUE TITLE
Failed on Github Action with TypeError while `poetry export`

### ISSUE THREAD

**Issue by Stewart86** [cjolowicz/nox-poetry#506]
A recent dependabot version bump has caused TypeError when running `nox` with `nox-poetry`, refer to Github Action log.

Here the nox session was trying to run a pre-commit session, however, this is effecting all other sessions.

I initially thought is was some version conflict, so I tried reverting dependencies one by one, nothing works. Than I re-run some other  past Github Actions that were successful, but also failed this time run.

So I figure, it might due to some changes to Github Actions, but due to my leak of knowledge on the underlying code, I could not resolve further. 

[here](https://github.com/Stewart86/aioCloudflare/actions) contains all the attempts on the runs.

```
nox > Running session pre-commit
nox > Creating virtual environment (virtualenv) using python3.9 in .nox/pre-commit
nox > poetry export --format=requirements.txt --dev --without-hashes
nox > Session pre-commit raised exception TypeError('slice indices must be integers or None or have an __index__ method')
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/nox/sessions.py", line 626, in execute
    self.func(session)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/nox/_decorators.py", line 54, in __call__
    return self.func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/nox_poetry/sessions.py", line 43, in wrapper
    function(proxy, *_args, **_kwargs)
  File "/home/runner/work/aioCloudflare/aioCloudflare/noxfile.py", line 77, in precommit
    session.install(
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/nox_poetry/sessions.py", line 290, in install
    return self.poetry.install(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/nox_poetry/sessions.py", line 149, in install
    requirements = self.export_requirements()
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/nox_poetry/sessions.py", line 224, in export_requirements
    constraints = to_constraints(self.poetry.export())
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/nox_poetry/sessions.py", line 90, in to_constraints
    return "\n".join(_to_constraints())
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/nox_poetry/sessions.py", line 86, in _to_constraints
    constraint = to_constraint(requirement, line)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/nox_poetry/sessions.py", line 68, in to_constraint
    requirement = Requirement(requirement_string)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/packaging/requirements.py", line 113, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pyparsing/core.py", line 1100, in parse_string
    loc, tokens = self._parse(instring, 0)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pyparsing/core.py", line 790, in _parseNoCache
    loc, tokens = self.parseImpl(instring, pre_loc, doActions)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pyparsing/core.py", line 3810, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pyparsing/core.py", line 790, in _parseNoCache
    loc, tokens = self.parseImpl(instring, pre_loc, doActions)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pyparsing/core.py", line 4024, in parseImpl
    return e._parse(
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pyparsing/core.py", line 790, in _parseNoCache
    loc, tokens = self.parseImpl(instring, pre_loc, doActions)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pyparsing/core.py", line 3810, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pyparsing/core.py", line 790, in _parseNoCache
    loc, tokens = self.parseImpl(instring, pre_loc, doActions)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pyparsing/core.py", line 4854, in parseImpl
    loc, tokens = self_expr._parse(instring, loc, doActions, callPreParse=False)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pyparsing/core.py", line 790, in _parseNoCache
    loc, tokens = self.parseImpl(instring, pre_loc, doActions)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pyparsing/core.py", line 3810, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pyparsing/core.py", line 827, in _parseNoCache
    tokens = fn(instring, tokens_start, ret_tokens)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pyparsing/core.py", line 283, in wrapper
    ret = func(*args[limit:])
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/packaging/requirements.py", line 81, in <lambda>
    lambda s, l, t: Marker(s[t._original_start : t._original_end])
TypeError: slice indices must be integers or None or have an __index__ method
nox > Session pre-commit failed.
Error: Process completed with exit code 1.
```

**Comment by cjolowicz** [comment]
Thanks for the report!

Please take a look at https://github.com/cjolowicz/cookiecutter-hypermodern-python/issues/1050 for some information about this issue.

You should be able to work around this crash by excluding pyparsing 3.0.5 from your dependencies. If that does not help, try pyparsing < 3.

**Comment by Stewart86** [comment]
Yes, I just saw that while you were replying. It works! I added `try pyparsing < 3` to constraint.txt.
Will close this for now. Thanks!
