### ISSUE TITLE
TypeError: slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by Zethson** [cjolowicz/nox-poetry#507]
Hi,

I am a little bit lost. Since about 1 week all of my nox CI jobs suddenly started failing. No new poetry nox or nox-poetry version has since been released. I cannot reproduce it locally and am not sure what is happening.

However, the issue seems to point at nox-poetry.

```
Run nox --force-color --python=3.8
nox > Running session pre-commit-3.8
nox > Creating virtual environment (virtualenv) using python3.8 in .nox/pre-commit-3-8
nox > poetry export --format=requirements.txt --dev --without-hashes
nox > Session pre-commit-3.8 raised exception TypeError('slice indices must be integers or None or have an __index__ method')
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nox/sessions.py", line 626, in execute
    self.func(session)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nox/_decorators.py", line 54, in __call__
    return self.func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nox_poetry/sessions.py", line 43, in wrapper
    function(proxy, *_args, **_kwargs)
  File "/home/runner/work/augurpy/augurpy/noxfile.py", line 82, in precommit
    session.install(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nox_poetry/sessions.py", line 290, in install
    return self.poetry.install(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nox_poetry/sessions.py", line 149, in install
    requirements = self.export_requirements()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nox_poetry/sessions.py", line 224, in export_requirements
    constraints = to_constraints(self.poetry.export())
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nox_poetry/sessions.py", line 90, in to_constraints
    return "\n".join(_to_constraints())
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nox_poetry/sessions.py", line 86, in _to_constraints
    constraint = to_constraint(requirement, line)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nox_poetry/sessions.py", line 68, in to_constraint
    requirement = Requirement(requirement_string)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/packaging/requirements.py", line 113, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pyparsing/core.py", line 1100, in parse_string
    loc, tokens = self._parse(instring, 0)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pyparsing/core.py", line 790, in _parseNoCache
    loc, tokens = self.parseImpl(instring, pre_loc, doActions)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pyparsing/core.py", line 3810, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pyparsing/core.py", line 790, in _parseNoCache
    loc, tokens = self.parseImpl(instring, pre_loc, doActions)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pyparsing/core.py", line 4024, in parseImpl
    return e._parse(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pyparsing/core.py", line 790, in _parseNoCache
    loc, tokens = self.parseImpl(instring, pre_loc, doActions)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pyparsing/core.py", line 3810, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pyparsing/core.py", line 790, in _parseNoCache
    loc, tokens = self.parseImpl(instring, pre_loc, doActions)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pyparsing/core.py", line 4854, in parseImpl
    loc, tokens = self_expr._parse(instring, loc, doActions, callPreParse=False)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pyparsing/core.py", line 790, in _parseNoCache
    loc, tokens = self.parseImpl(instring, pre_loc, doActions)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pyparsing/core.py", line 3810, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pyparsing/core.py", line 827, in _parseNoCache
    tokens = fn(instring, tokens_start, ret_tokens)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pyparsing/core.py", line 283, in wrapper
    ret = func(*args[limit:])
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/packaging/requirements.py", line 81, in <lambda>
    lambda s, l, t: Marker(s[t._original_start : t._original_end])
TypeError: slice indices must be integers or None or have an __index__ method
nox > Session pre-commit-3.8 failed.
Error: Process completed with exit code 1.
```

Do you have any idea?

**Comment by Zethson** [comment]
Ah, now I can reproduce it locally. I never run into this issue when I install my projects which must up/downgrade some dependency that nox-poetry apparently fails with.

**Comment by cjolowicz** [comment]
This is caused by incompatible versions of packaging and pyparsing.

See #506

**Comment by Zethson** [comment]
Oh, I did not see this.
Sorry and thank you!

**Comment by cjolowicz** [comment]
no worries!
